Issue8
erickpintor/ExercicioRefatoracaoBanco pull request #10
Opened 2019-06-06 12:58 UTC by gustavohd18

2019-06-06 13:21 UTC, lucas-loges requested changes
bobão

2019-06-17 01:19 UTC, erickpintor requested changes

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/Operacao.java
> +	private final List<Operacao> operacoes;
Uma operação não deve conhecer as outras operações.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/Operacao.java
> +	private Persistencia persistencia;
Operação não deve conhecer a persistência.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/Operacao.java
> +	private Persistencia persistencia;
Isso é parte do controlador de operações.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/ContaEstatistica.java
> +    public void setNumeroConta(int numeroConta){
Pq os sets se ninguém usa?

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/Fachada.java
> +            e.printStackTrace();
Não segura exceções não. Deixa quebra. Retornar null não quer dizer que a conta não existe, não que algo deu errado.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/Fachada.java
> +            e.printStackTrace();
Mesma coisa aqui sobre exceções.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/Fachada.java
> +            e.printStackTrace();
Mesma coisa aqui sobre exceções.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/Fachada.java
> +            e.printStackTrace();
Mesma coisa aqui sobre exceções.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/Fachada.java
> +            e.printStackTrace();
Mesma coisa aqui sobre exceções.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/OperacaoController.java
> +            if (operacaoConta.getAno() == ano) {}
E esse `{}` no final `if`? haha

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/OperacaoController.java
> +	public void AddOperacao(int dia, int mes, int ano, int hora, int minuto, int segundo, int numeroConta, int statusConta,
`Add` deve ser `add` por convenção.

2019-06-17 01:19 UTC, erickpintor commented on src/main/java/com/bcopstein/ExercicioRefatoracaoBanco/negocio/ContaController.java
> +    public void DebitoConta(int numeroConta, double valor) throws ContaException {
Deve ser `debidoConta` por convenção.

2019-06-30 21:15 UTC, erickpintor approved these changes
Pode fazer o merge.

2019-06-30 22:03 UTC, merged